### ISSUE TITLE
NVWL Collection

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/fin-example-repository#15]
We need to create a new collection from the Napa Valley Wine Collection,  For now this will be and example repo, but we need to work this into gitlab at a later date.

**Comment by EricNebeker** [comment]
@qjhart I pushed metadata additions to the gitlab repository. I expanded the collection description, but we might want to ask Axel or someone more familiar with the reports and the association to provide one that is more robust. Also, the lcna id for sdPublisher is for special collections. There is uncertainty about what department these will end up in, so we might need to change that.

**Comment by qjhart** [comment]
Moved  to https://gitlab.dams.library.ucdavis.edu/dams/nvwl/issues/2
